# ------------------------------
# .pre-commit-config.yaml
# ------------------------------
# Pre-commit configuration file that defines hooks
# for linting, formatting, and security scanning.

repos:
  # -------------------------------------------
  # 1. Basic file checks: YAML, TOML, EOF, whitespace
  # -------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
       - id: check-yaml              # check YAML file validity
       - id: check-toml              # check TOML file validity
       - id: end-of-file-fixer       # ensure files end with a newline
       - id: trailing-whitespace     # remove trailing whitespace


  # -------------------------------------------
  # 2. Import sorting
  # -------------------------------------------
  - repo: https://github.com/PyCQA/isort.git
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile=black"]

  # -------------------------------------------
  # 3. Black code formatter
  # -------------------------------------------
  - repo: https://github.com/psf/black.git
    rev: 25.11.0
    hooks:
      - id: black

  # -------------------------------------------
  # 4. Linting with Flake8
  # -------------------------------------------
  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--extend-ignore=E203,W503,E501"]

  # -------------------------------------------
  # 5. Ruff linter and formatter (fast Python tool)
  # -------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.14.4
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]

  # -------------------------------------------
  # 6. Secret scanning / security (Gitleaks)
  # -------------------------------------------
  - repo: https://github.com/gitleaks/gitleaks.git
    rev: v8.29.0
    hooks:
      - id: gitleaks
